### PR TITLE
Gulp task now actually finishes

### PR DESCRIPTION
**Pull request by mvdstam**
This fixes issue #6.

### CODE REVIEW

**Comment by mikeerickson** [comment]
Thanks, will get this reviewed and merged

**Comment by mvdstam** [comment]
Great! I believe https://github.com/mikeerickson/gulp-behat should get the same fix by the way. What do you think?

**Comment by mikeerickson** [comment]
I have implemented this fix in the master source (which hasn't been committed but has some other tweaks).   Thx for the fix thouh @mvdstam 

And, I have also added it to the gulp-behat master source as well :-)

**Comment by mvdstam** [comment]
I'm not sure what you mean with "the master source", but could you at least please push those fixes to npm so everyone can benefit from this?

**Comment by mikeerickson** [comment]
I will be releasing later today

**Pull request closed without merging**
